site_name: 'SITE TITLE'
site_description: "SITE DESCRIPTION"
site_author: "Rock Solid Knowledge"
copyright: "Copyright &copy; 2021 <a class='font-bold' href='https://www.rocksolidknowledge.com' target='_blank' rel='noopener'>Rock Solid Knowledge</a>"
gtm_key: 'GTM-MDF5JFF'
plugins:
    - search
markdown_extensions:
    - admonition
    - markdown_fenced_code_tabs:
        single_block_as_tab: False
        active_class: 'active'
        template: 'default'
extra:
    version: 1.2.0